sudo: required
language: generic

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=stable

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/
    - /^upstream.*/